In [2]:
# Import dependencies

import pandas as pd

In [3]:
# Reference to CSV and reading CSV into Pandas DataFrame
csv_path1 = "Resources/country_vaccinations.csv"
csv_path2 = "Resources/gdp-csv.csv"
csv_path3 = "Resources/time_series_covid_19_confirmed.csv"
csv_path4 = "Resources/time_series_covid_19_deaths.csv"
csv_path5 = "Resources/time_series_covid_19_recovered.csv"
csv_path6 = "Resources/WorldPopulation.csv"
csv_path7 = "Resources/country_vaccinations_by_manufacturer.csv"


# merging final combined CSV meta file


country_vaccinations_df = pd.read_csv(csv_path1)
gdp_df = pd.read_csv(csv_path2)
covid_19_confirmed_df = pd.read_csv(csv_path3)
covid_19_deaths_df = pd.read_csv(csv_path4)
covid_19_recovered_df = pd.read_csv(csv_path5)
WorldPopulations_df = pd.read_csv(csv_path6)
country_vaccinations_by_manufacturer_df = pd.read_csv(csv_path7)

In [4]:
country_vaccinations_df.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2/22/2021,0.0,0.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2/23/2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2/24/2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2/25/2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2/26/2021,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,35.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",World Health Organization,https://covid19.who.int/

In [5]:
gdp_df.head()

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Last Updated Date,4/26/2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2.011000e+03,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03,2.016000e+03,2.017000e+03,2018.0,2019.0,2020.0
4,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.549721e+09,2.534637e+09,2.701676e+09,2.765363e+09,2.919553e+09,2.965922e+09,3.056425e+09,NaN,NaN,NaN

In [6]:
 country_vaccinations_df.dropna()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
118,Albania,ALB,2/18/2021,3049.0,2438.0,611.0,1348.0,254.0,0.11,0.08,0.02,88.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
200,Albania,ALB,5/11/2021,622507.0,440921.0,181586.0,9548.0,12160.0,21.63,15.32,6.31,4225.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
201,Albania,ALB,5/12/2021,632676.0,444755.0,187921.0,10169.0,10870.0,21.98,15.45,6.53,3777.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
202,Albania,ALB,5/13/2021,638338.0,445402.0,192936.0,5662.0,9445.0,22.18,15.48,6.70,3282.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
203,Albania,ALB,5/14/2021,653330.0,448571.0,204759.0,14992.0,9662.0,22.70,15.59,7.12,3357.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinovac, ...",Ministry of Health,https://shendetesia.gov.al/vaksinimi-anticovid...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19111,Zimbabwe,ZWE,5/15/2021,793311.0,579769.0,213542.0,18070.0,19353.0,5.34,3.90,1.44,1302.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1395107134...
19112,Zimbabwe,ZWE,5/16/2021,796947.0,581615.0,215332.0,3636.0,16101.0,5.36,3.91,1.45,1083.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1395107134...
19113,Zimbabwe,ZWE,5/17/2021,814258.0,591808.0,222450.0,17311.0,17658.0,5.48,3.98,1.50,1188.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1395107134...
19114,Zimbabwe,ZWE,5/18/2021,831954.0,600579.0,231375.0,17696.0,17455.0,5.60,4.04,1.56,1174.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1395107134...
19115,Zimbabwe,ZWE,5/19/2021,844684.0,605556.0,239128.0,12730.0,16331.0,5.68,4.07,1.61,1099.0,Sinopharm/Beijing,Ministry of Health,https://twitter.com/MoHCCZim/status/1395107134...

In [7]:
country_data_df= country_vaccinations_df[["country","date","iso_code","total_vaccinations","people_vaccinated","people_fully_vaccinated","daily_vaccinations_raw","daily_vaccinations"]].drop_duplicates
country_data()

NameError: name 'country_data' is not defined

In [8]:
clean_data =country_vaccinations_df[["country","date","iso_code","total_vaccinations","people_vaccinated","people_fully_vaccinated","daily_vaccinations_raw","daily_vaccinations"]].dropna()

In [9]:
print(clean_data)

        country       date iso_code  total_vaccinations  people_vaccinated  \
118     Albania  2/18/2021      ALB              3049.0             2438.0
200     Albania  5/11/2021      ALB            622507.0           440921.0
201     Albania  5/12/2021      ALB            632676.0           444755.0
202     Albania  5/13/2021      ALB            638338.0           445402.0
203     Albania  5/14/2021      ALB            653330.0           448571.0
...         ...        ...      ...                 ...                ...
19111  Zimbabwe  5/15/2021      ZWE            793311.0           579769.0
19112  Zimbabwe  5/16/2021      ZWE            796947.0           581615.0
19113  Zimbabwe  5/17/2021      ZWE            814258.0           591808.0
19114  Zimbabwe  5/18/2021      ZWE            831954.0           600579.0
19115  Zimbabwe  5/19/2021      ZWE            844684.0           605556.0

       people_fully_vaccinated  daily_vaccinations_raw  daily_vaccinations
118                      611.0                  1348.0               254.0
200                   181586.0                  9548.0             12160.0
201                   187921.0                 10169.0             10870.0
202                   192936.0                  5662.0              9445.0
203                   204759.0                 14992.0              9662.0
...                        ...                     ...                 ...
19111                 213542.0                 18070.0             19353.0
19112                 215332.0                  3636.0             16101.0
19113                 222450.0                 17311.0             17658.0
19114                 231375.0                 17696.0             17455.0
19115                 239128.0                 12730.0             16331.0

[6855 rows x 8 columns]

In [10]:
country_number = len(clean_data["country"].unique())
country_number

113

In [11]:
clean_data.groupby('country').agg({'people_fully_vaccinated': ['mean', 'median','std','var','sem']})

              people_fully_vaccinated                                          \
                                 mean      median           std           var
country
Albania                  1.660948e+05    190428.5  8.275632e+04  6.848609e+09
Andorra                  4.484000e+03      4484.0           NaN           NaN
Argentina                6.451340e+05    635579.0  4.761291e+05  2.266989e+11
Aruba                    2.173257e+04     20933.5  6.965505e+03  4.851825e+07
Austria                  4.273306e+05    310979.5  3.329518e+05  1.108569e+11
...                               ...         ...           ...           ...
United States            5.157684e+07  43589023.0  3.912816e+07  1.531013e+15
Uruguay                  4.593641e+05    447360.0  3.200455e+05  1.024291e+11
Vietnam                  1.888050e+04     21777.0  6.354871e+03  4.038439e+07
Wales                    3.408921e+05    304411.0  3.122219e+05  9.748251e+10
Zimbabwe                 7.352397e+04     36778.0  7.053099e+04  4.974621e+09


                        sem
country
Albania        3.378513e+04
Andorra                 NaN
Argentina      4.519217e+04
Aruba          1.316357e+03
Austria        2.989995e+04
...                     ...
United States  3.571896e+06
Uruguay        4.355267e+04
Vietnam        3.177436e+03
Wales          2.792598e+04
Zimbabwe       9.182353e+03

[113 rows x 5 columns]

In [12]:
clean_data.groupby('country').agg({'people_fully_vaccinated': ['max', 'min','sum']})

              people_fully_vaccinated
                                  max        min           sum
country
Albania                      228756.0      611.0  9.965690e+05
Andorra                        4484.0     4484.0  4.484000e+03
Argentina                   2103964.0    16352.0  7.160987e+07
Aruba                         37324.0    12025.0  6.085120e+05
Austria                     1129198.0        1.0  5.298900e+07
...                               ...        ...           ...
United States             125453423.0  1342086.0  6.189221e+09
Uruguay                      961943.0      374.0  2.480566e+07
Vietnam                       22561.0     9407.0  7.552200e+04
Wales                        939072.0       97.0  4.261151e+07
Zimbabwe                     239128.0      280.0  4.337914e+06

[113 rows x 3 columns]

In [13]:
clean_data[(clean_data['date']> "2021-05-01")]

,country,date,iso_code,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations
200,Albania,5/11/2021,ALB,622507.0,440921.0,181586.0,9548.0,12160.0
201,Albania,5/12/2021,ALB,632676.0,444755.0,187921.0,10169.0,10870.0
202,Albania,5/13/2021,ALB,638338.0,445402.0,192936.0,5662.0,9445.0
203,Albania,5/14/2021,ALB,653330.0,448571.0,204759.0,14992.0,9662.0
207,Albania,5/18/2021,ALB,688947.0,460191.0,228756.0,8864.0,9491.0
...,...,...,...,...,...,...,...,...
19111,Zimbabwe,5/15/2021,ZWE,793311.0,579769.0,213542.0,18070.0,19353.0
19112,Zimbabwe,5/16/2021,ZWE,796947.0,581615.0,215332.0,3636.0,16101.0
19113,Zimbabwe,5/17/2021,ZWE,814258.0,591808.0,222450.0,17311.0,17658.0
19114,Zimbabwe,5/18/2021,ZWE,831954.0,600579.0,231375.0,17696.0,17455.0
19115,Zimbabwe,5/19/2021,ZWE,844684.0,605556.0,239128.0,12730.0,16331.0

In [38]:
 new_data=clean_data[(clean_data['date']< "2021-05-01")]
print(new_data)

         country       date  iso_code  total_vaccinations  people_vaccinated  \
118      Albania  2/18/2021       ALB              3049.0             2438.0
632    Argentina  1/21/2021       ARG            265724.0           249372.0
633    Argentina  1/22/2021       ARG            279602.0           254456.0
634    Argentina  1/23/2021       ARG            288064.0           258876.0
635    Argentina  1/24/2021       ARG            292023.0           260036.0
...          ...        ...       ...                 ...                ...
18848      Wales  2/24/2021  OWID_WLS            959121.0           889270.0
18849      Wales  2/25/2021  OWID_WLS            982396.0           902334.0
18850      Wales  2/26/2021  OWID_WLS           1005389.0           916336.0
18851      Wales  2/27/2021  OWID_WLS           1020023.0           923615.0
18852      Wales  2/28/2021  OWID_WLS           1029488.0           925669.0

       people_fully_vaccinated  daily_vaccinations_raw  daily_vaccinations
118                      611.0                  1348.0               254.0
632                    16352.0                 17791.0             11704.0
633                    25146.0                 13878.0             11263.0
634                    29188.0                  8462.0             11124.0
635                    31987.0                  3959.0             10342.0
...                        ...                     ...                 ...
18848                  69851.0                 21336.0             16735.0
18849                  80062.0                 23275.0             16843.0
18850                  89053.0                 22993.0             17069.0
18851                  96408.0                 14634.0             17452.0
18852                 103819.0                  9465.0             17784.0

[1782 rows x 8 columns]

In [44]:
vaccine_data =new_data[['country','date','total_vaccinations','people_fully_vaccinated']]
print(vaccine_data)

         country       date  total_vaccinations  people_fully_vaccinated
118      Albania  2/18/2021              3049.0                    611.0
632    Argentina  1/21/2021            265724.0                  16352.0
633    Argentina  1/22/2021            279602.0                  25146.0
634    Argentina  1/23/2021            288064.0                  29188.0
635    Argentina  1/24/2021            292023.0                  31987.0
...          ...        ...                 ...                      ...
18848      Wales  2/24/2021            959121.0                  69851.0
18849      Wales  2/25/2021            982396.0                  80062.0
18850      Wales  2/26/2021           1005389.0                  89053.0
18851      Wales  2/27/2021           1020023.0                  96408.0
18852      Wales  2/28/2021           1029488.0                 103819.0

[1782 rows x 4 columns]