In [1]:
# apps
import pandas as pd
import numpy as np

In [2]:
# get data sets
path_gdp = "../Resources/gdp-csv.csv"
path_pop = "../Resources/WorldPopulation.csv"
path_locs = "../Resources/time_series_covid_19_deaths.csv"

gdp_raw_df = pd.read_csv(path_gdp, skiprows=4)
#gdp_raw_df.head(15)
pop_raw_df = pd.read_csv(path_pop)
#pop_raw_df.head(15)
#pop_raw_df.loc[pop_raw_df["Country Name"] == "Wallis"]
locs_raw_df = pd.read_csv(path_locs)
#locs_raw_df.head()
#locs_raw_df.loc[locs_raw_df["Country/Region"] == "France"]
#locs_raw_df.loc[locs_raw_df["Province/State"] == "Wallis and Futuna"]

In [3]:
# get just desired columns
#gdp
gdp_gdp_2019 = []
gdp_country_2019 = []
gdp_code_2019 = []

counter = len(gdp_raw_df["2019"])
#print(counter)

for i in np.arange(counter):
    gdp = gdp_raw_df["2019"][i]
    gdp_gdp_2019.append(gdp)  
    country = gdp_raw_df["Country Name"][i]
    gdp_country_2019.append(country)
    code = gdp_raw_df["Country Code"][i]
    gdp_code_2019.append(code)

#gdp df
gdp_raw_2019_df = pd.DataFrame({"Country": gdp_country_2019,
                                "Code": gdp_code_2019,
                                "2019 GDP":gdp_gdp_2019
                                })

gdp_raw_2019_df.head(15)
gdp_raw_2019_df.shape

(264, 3)

In [4]:
#get just desired columns
#pop
pop_pop_2019 = []
pop_country_2019 = []
pop_code_2019 = []

counter = len(pop_raw_df["2019"])
#print(counter)

for i in np.arange(counter):
    pop = pop_raw_df["2019"][i]
    pop_pop_2019.append(pop)  
    country = pop_raw_df["Country Name"][i]
    pop_country_2019.append(country)
    code = pop_raw_df["Country Code"][i]
    pop_code_2019.append(code)
    
pop_raw_2019_df = pd.DataFrame({"Country": pop_country_2019,
                                "Code": pop_code_2019,
                                "2019 Population":pop_pop_2019
                                })

pop_raw_2019_df.head(15)
pop_raw_2019_df.shape

(264, 3)

In [6]:
#get just desired columns
#locs
locs_lat_2019 = []
locs_lon_2019 = []
locs_country_2019 = []
locs_state_2019 = []
deaths_5121 = []

counter = len(locs_raw_df["Country/Region"])
#print(counter)

for i in np.arange(counter):
    lat = locs_raw_df["Lat"][i]
    locs_lat_2019.append(lat)  
    lon = locs_raw_df["Long"][i]
    locs_lon_2019.append(lon)
    country = locs_raw_df["Country/Region"][i]
    locs_country_2019.append(country)
    state = locs_raw_df["Province/State"][i]
    locs_state_2019.append(state)
    deaths = locs_raw_df["5/1/21"][i]
    deaths_5121.append(deaths)
    
locs_raw_5121_df = pd.DataFrame({"Country": locs_country_2019,
                                "State": locs_state_2019,
                                "Latitude":locs_lat_2019,
                                 "Longitude":locs_lon_2019,
                                 "Deaths to 5/1/21": deaths_5121
                                })

locs_raw_5121_df.head()
locs_clean_5121_df = locs_raw_5121_df.copy()
locs_clean_5121_df.loc[locs_clean_5121_df["Country"] == "Canada"]

   Country                      State  Latitude  Longitude  Deaths to 5/1/21
39  Canada                    Alberta   53.9333  -116.5765              2083
40  Canada           British Columbia   53.7267  -127.6476              1581
41  Canada           Diamond Princess    0.0000     0.0000                 1
42  Canada             Grand Princess    0.0000     0.0000                 0
43  Canada                   Manitoba   53.7609   -98.8139               976
44  Canada              New Brunswick   46.5653   -66.4619                36
45  Canada  Newfoundland and Labrador   53.1355   -57.6604                 6
46  Canada      Northwest Territories   64.8255  -124.8457                 0
47  Canada                Nova Scotia   44.6820   -63.7443                67
48  Canada                    Nunavut   70.2998   -83.1076                 4
49  Canada                    Ontario   51.2538   -85.3232              8062
50  Canada       Prince Edward Island   46.5107   -63.4168                 0
51  Canada                     Quebec   52.9399   -73.5491             10933
52  Canada     Repatriated Travellers       NaN        NaN                 0
53  Canada               Saskatchewan   52.9399  -106.4509               494
54  Canada                      Yukon   64.2823  -135.0000                 2

In [152]:
#clean location and deaths
#australia
australia = locs_raw_5121_df.loc[locs_raw_5121_df["Country"] == "Australia"]
australia_lat = australia["Latitude"].mean()
#print(australia_lat)
australia_lon = australia["Longitude"].mean()
#print(australia_lon)
australia_deaths = australia["Deaths to 5/1/21"].sum()
#print(australia_deaths)
#print(australia)
locs_clean_5121_df.drop(locs_clean_5121_df.loc[9:15].index, inplace=True)
locs_clean_5121_df.loc[8,"Latitude"] = australia_lat
locs_clean_5121_df.loc[8,"Longitude"] = australia_lon
locs_clean_5121_df.loc[8,"Deaths to 5/1/21"] = australia_deaths
#canada
canada = locs_raw_5121_df.loc[locs_raw_5121_df["Country"] == "Canada"]
canada_lat = canada["Latitude"].mean()
#print(canada_lat)
canada_lon = canada["Longitude"].mean()
#print(canada_lon)
canada_deaths = canada["Deaths to 5/1/21"].sum()
#print(canada_deaths)
locs_clean_5121_df.drop(locs_clean_5121_df.loc[40:54].index, inplace=True)
locs_clean_5121_df.loc[39,"Latitude"] = canada_lat
locs_clean_5121_df.loc[39,"Longitude"] = canada_lon
locs_clean_5121_df.loc[39,"Deaths to 5/1/21"] = canada_deaths
#china
locs_raw_5121_df.loc[70,"Country"] = "Hong Kong"
locs_clean_5121_df.loc[70,"Country"] = "Hong Kong"
#
china = locs_raw_5121_df.loc[locs_raw_5121_df["Country"] == "China"]
china_lat = china["Latitude"].mean()
#print(china_lat)
china_lon = china["Longitude"].mean()
#print(china_lon)
china_deaths = china["Deaths to 5/1/21"].sum()
#print(china_deaths)
locs_clean_5121_df.drop(locs_clean_5121_df.loc[59:69].index, inplace=True)
locs_clean_5121_df.drop(locs_clean_5121_df.loc[71:91].index, inplace=True)
locs_clean_5121_df.loc[58,"Latitude"] = china_lat
locs_clean_5121_df.loc[58,"Longitude"] = china_lon
locs_clean_5121_df.loc[58,"Deaths to 5/1/21"] = china_deaths
#Denmark
locs_raw_5121_df.loc[103,"Country"] = "Greenland"
locs_clean_5121_df.loc[103,"Country"] = "Greenland"
locs_raw_5121_df.loc[104,"Deaths to 5/1/21"] = "2490"
locs_clean_5121_df.loc[104,"Deaths to 5/1/21"] = "2490"
locs_clean_5121_df.drop(locs_clean_5121_df.loc[102:102].index, inplace=True)
#France
locs_raw_5121_df.loc[120,"Country"] = "French Polynesia"
locs_clean_5121_df.loc[120,"Country"] = "French Polynesia"
locs_raw_5121_df.loc[128,"Country"] = "St. Martin (French part)"
locs_clean_5121_df.loc[128,"Country"] = "St. Martin (French part)"
france = locs_raw_5121_df.loc[locs_raw_5121_df["Country"] == "France"]
france_deaths = france["Deaths to 5/1/21"].sum()
#print(france_deaths)
locs_clean_5121_df.drop(locs_clean_5121_df.loc[119:119].index, inplace=True)
locs_clean_5121_df.drop(locs_clean_5121_df.loc[121:127].index, inplace=True)
locs_clean_5121_df.drop(locs_clean_5121_df.loc[129:129].index, inplace=True)
locs_clean_5121_df.loc[130,"Deaths to 5/1/21"] = france_deaths
#Netherlands
locs_raw_5121_df.loc[192,"Country"] = "Aruba"
locs_clean_5121_df.loc[192,"Country"] = "Aruba"
locs_raw_5121_df.loc[194,"Country"] = "Curacao"
locs_clean_5121_df.loc[194,"Country"] = "Curacao"
locs_raw_5121_df.loc[195,"Country"] = "Sint Maarten"
locs_clean_5121_df.loc[195,"Country"] = "Sint Maarten"
locs_raw_5121_df.loc[196,"Deaths to 5/1/21"] = 17185
locs_clean_5121_df.loc[196,"Deaths to 5/1/21"] = 17185
locs_clean_5121_df.drop(locs_clean_5121_df.loc[193:193].index, inplace=True)
#United Kingdom
locs_raw_5121_df.loc[255,"Country"] = "Bermuda"
locs_clean_5121_df.loc[255,"Country"] = "Bermuda"
locs_raw_5121_df.loc[257,"Country"] = "Cayman Islands"
locs_clean_5121_df.loc[257,"Country"] = "Cayman Islands"
locs_raw_5121_df.loc[260,"Country"] = "Gibraltar"
locs_clean_5121_df.loc[260,"Country"] = "Gibraltar"
locs_raw_5121_df.loc[261,"Country"] = "Isle of Man"
locs_clean_5121_df.loc[261,"Country"] = "Isle of Man"
locs_raw_5121_df.loc[264,"Country"] = "Turks and Caicos Islands"
locs_clean_5121_df.loc[264,"Country"] = "Turks and Caicos Islands"
locs_raw_5121_df.loc[263,"Country"] = "United Kingdom"
locs_clean_5121_df.loc[263,"Country"] = "United Kingdom"

uk = locs_raw_5121_df.loc[locs_raw_5121_df["Country"] == "United Kingdom"]
uk_deaths = uk["Deaths to 5/1/21"].sum()
#print(uk_deaths)
locs_clean_5121_df.loc[265,"Deaths to 5/1/21"] = uk_deaths
#
locs_clean_5121_df.drop(locs_clean_5121_df.loc[254:254].index, inplace=True)
locs_clean_5121_df.drop(locs_clean_5121_df.loc[256:256].index, inplace=True)
locs_clean_5121_df.drop(locs_clean_5121_df.loc[258:259].index, inplace=True)
locs_clean_5121_df.drop(locs_clean_5121_df.loc[262:263].index, inplace=True)
#
#locs_clean_5121_df.loc[locs_clean_5121_df["Country"] == "United Kingdom"]
#locs_raw_5121_df.loc[locs_raw_5121_df["Country"] == "China"]
locs_clean_5121_a_df = locs_clean_5121_df.copy()
locs_clean_5121_a_df.head()
#locs_clean_5121_a_df.to_csv("deaths_loc_country.csv", index=False)

       Country State  Latitude  Longitude Deaths to 5/1/21
0  Afghanistan   NaN  33.93911  67.709953             2631
1      Albania   NaN  41.15330  20.168300             2396
2      Algeria   NaN  28.03390   1.659600             3261
3      Andorra   NaN  42.50630   1.521800              125
4       Angola   NaN -11.20270  17.873900              600

In [146]:
#new clean loc
locs_clean_country = []
locs_clean_state = []
locs_clean_lat = []
locs_clean_long = []
locs_clean_deaths = []
locs_clean_country = locs_clean_5121_a_df["Country"].tolist()
locs_clean_state = locs_clean_5121_a_df["State"].tolist()
locs_clean_lat = locs_clean_5121_a_df["Latitude"].tolist()
locs_clean_lon = locs_clean_5121_a_df["Longitude"].tolist()
locs_clean_deaths = locs_clean_5121_a_df["Deaths to 5/1/21"].tolist()
#locs_clean_deaths

In [9]:
#list of countries for vaccine sheet
path_vacs = "../Resources/country_vaccinations.csv"

vacs_raw_df = pd.read_csv(path_vacs)
#vacs_raw_df.head(15)

#just lines for 5/1/2021
vacs_raw_512021_df = vacs_raw_df.loc[vacs_raw_df['date']== '5/1/2021']
#vacs_raw_512021_df.head(5)
#vacs_raw_df.loc[vacs_raw_df['country'] == 'Yemen'] ------add
#vacs_raw_df.loc[vacs_raw_df['country'] == 'Wallis and Futuna']

In [126]:
#just needed columns for vaccine list
#vacs
vacs_country_5121 = []
vacs_code_5121 = []
vacs_total_5121 =[]
vacs_full_5121 = []
vacs_vacs_5121 = []

counter = len(vacs_raw_512021_df["country"])
#print(counter)
vacs_5121_index = vacs_raw_512021_df.index.tolist()

for i in vacs_5121_index:
    country = vacs_raw_512021_df["country"][i]
    vacs_country_5121.append(country)  
    code = vacs_raw_512021_df["iso_code"][i]
    vacs_code_5121.append(code)
    total = vacs_raw_512021_df["total_vaccinations"][i]
    vacs_total_5121.append(total)
    full = vacs_raw_512021_df["people_fully_vaccinated"][i]
    vacs_full_5121.append(full)
    vacs = vacs_raw_512021_df["vaccines"][i]
    vacs_vacs_5121.append(vacs)
    
#print(vacs_vacs_5121)

vacs_raw_5121_df = pd.DataFrame({"Country": vacs_country_5121,
                                "Code": vacs_code_5121,
                                "Total Vaccinations": vacs_total_5121,
                                "Total Fully Vaccinated": vacs_full_5121,
                                "Vaccinations Used": vacs_vacs_5121
                                })
#vacs_raw_5121_df.head(20)

In [139]:
#split vaccine types
#get list of vaccines
vac_type_list = []
counts_list = []
counts_list_entry = []
country_entry = []
country_l = []

counter = len(vacs_raw_5121_df["Vaccinations Used"])
#print(counter)

#separate vaccines and list
for i in np.arange(counter):
    first = vacs_raw_5121_df["Vaccinations Used"][i]
    first_l = first.strip('()').split(',')
    country = vacs_raw_5121_df["Country"][i]
    country_l.append(country)
    counts= len(first_l)
    counts_list.append(counts)
    for j in np.arange(counts):
        vac_type_list.append(first_l[j])
        country_entry.append(country)
        counts_list_entry.append(counts)
        
#vac_type_list
#counts_list_entry
#country_entry
#len(vac_type_list)
#len(country_entry)
#len(counts_list_entry)

vacs_used_country = pd.DataFrame({"Country": country_l,
                                 "Vaccine Type Count": counts_list
                                 })

vac_type_used = pd.DataFrame({"Country": country_entry,
                             "Vaccine Used": vac_type_list,
                             "Number of Vaccines Used": counts_list_entry
                             })

vac_type_used["Vaccine Used"]=vac_type_used["Vaccine Used"].str.replace(' ', '')

vac_type_list1 =[]
vacs = vac_type_used["Vaccine Used"].unique()
vac_type_list1 = vacs.tolist()
vac_type_list1
vac_type_used_group = vac_type_used.groupby('Vaccine Used').count()
#print(vac_type_used_group)
vaccine_type = []
vaccine_type = vac_type_used_group.index.tolist()
#vaccine_type
country_vac_count = []
country_vac_count = vac_type_used_group["Country"].tolist()
country_vac_count


#vac_type_used.loc[vac_type_used["Vaccine Used"] == "Moderna"]

types_of_vaccines_usage = pd.DataFrame({"Vaccine": vaccine_type,
                                       "Countries Using": country_vac_count
                                       })
types_of_vaccines_usage.sort_values(by=["Countries Using"], ascending=[False])

#types_of_vaccines_usage.to_csv("types_of_vaccines.csv", index=False)
#vacs_used_country.to_csv("vacs_used_country.csv", index=False)
#vac_type_used.to_csv("vac_type_used.csv", index=False)
#vac_type_used
#vacs_used_country.sort_values(by=["Vaccine Type Count"], ascending=[False])

In [13]:
#country names analysis
#for each source
list_name = []
list_source = []

for name in gdp_country_2019:
    list_name.append(name)
    list_source.append("gdp_name")
    
for name in pop_country_2019:
    list_name.append(name)
    list_source.append("pop_name")
    
for name in locs_country_2019:
    list_name.append(name)
    list_source.append("loc_name")
    
for name in locs_state_2019:
    list_name.append(name)
    list_source.append("loc_state")
    
for name in vacs_country_5121:
    list_name.append(name)
    list_source.append("vacs_name")
    
#len(list_name)

country_names = pd.DataFrame({"Country Name": list_name,
                           "Source": list_source
                            })
country_name_nan = country_names.dropna()
country1 = country_name_nan.groupby('Country Name').count()
country1.sort_values("Source")
country1.loc[country1["Source"] == 4]
#country_names.loc[country_names["Country Name"] == "Timor"]
#search = country_names["Country Name"].str.contains("russi")
#country_names[search]
#country_name_nan.head(20)
#country_name_nan.shape

                     Source
Country Name
Afghanistan               4
Albania                   4
Andorra                   4
Angola                    4
Antigua and Barbuda       4
...                     ...
Uruguay                   4
Uzbekistan                4
Vietnam                   4
Zambia                    4
Zimbabwe                  4

[146 rows x 1 columns]

In [13]:
#country name changes needed
search = country_name_nan["Country Name"].str.contains("zbeki")
country_name_nan[search]

     Country Name     Source
250    Uzbekistan   gdp_name
514    Uzbekistan   pop_name
795    Uzbekistan   loc_name
1262   Uzbekistan  vacs_name

In [144]:
#administered vacs
#vacs_raw_df.head()
vacs_country_v = []
vacs_fully_v = []
vacs_date_v = []
counterv= len(vacs_raw_df["country"])
#print(counterv)

#for i in np.arange(counterv):
vacs_country_v = vacs_raw_df["country"].tolist()
#    vacs_country_v.append(country_v)
vacs_fully_v = vacs_raw_df["people_fully_vaccinated"].tolist()
#    vacs_fully_v.append(fully_v)
vacs_date_v = vacs_raw_df["date"].tolist()
#    vacs_date_v.append(vacs_date_v)
    
vacs_full_df = pd.DataFrame({"Country": vacs_country_v,
                            "Fully Vaccinated": vacs_fully_v,
                            "Date Reported": vacs_date_v
                            })

#vacs_full_df.head()
counterf=len(vacs_full_df["Country"])
#print(counterf)
#vacs_full_gb_df = vacs_full_df.groupby(["Country"])["Fully Vaccinated"].max()
#vacs_full_gb_df
countryf = vacs_full_df.groupby(["Country"]).count()
#countryf["Fully Vaccinated"].max()
country_fl = countryf.index.tolist()
#country_fl
countryfmx = vacs_full_df.groupby(["Country"])
vacs_fmx = countryfmx["Fully Vaccinated"].max()
vacs_fmx_l = vacs_fmx.tolist()
#vacs_fmx_l
#vacs_raw_df.head()
#vacs_fmx
reported_vacs = pd.DataFrame({"Country": country_fl,
                             "Reported Full Vacs": vacs_fmx_l
                             })
reported_vacs["Reported Full Vacs"]=reported_vacs["Reported Full Vacs"].fillna(0)
reported_vacs1= reported_vacs
#reported_vacs1.to_csv("reported_vacs.csv", index=False)

In [51]:
#country names analysis cleaned
#for each source
list_name_clean = []
list_source_clean = []

#for name in gdp_country_2019:
#    list_name_clean.append(name)
#    list_source_clean.append("gdp_name")
    
#for name in pop_country_2019:
#    list_name_clean.append(name)
#    list_source_clean.append("pop_name")
    
for name in locs_clean_country:
    list_name_clean.append(name)
    list_source_clean.append("loc_name_c")
    
#for name in locs_clean_state:
#    list_name_clean.append(name)
#    list_source_clean.append("loc_state_c")
    
for name in country_fl:
    list_name_clean.append(name)
    list_source_clean.append("vacs_name_c")
    
#len(list_name)

country_names_clean = pd.DataFrame({"Country Name": list_name_clean,
                                    "Source": list_source_clean
                                    })
country_name_clean_nan = country_names_clean.dropna()
country1_clean = country_name_clean_nan.groupby('Country Name').count()
country1_clean.sort_values("Source")
country1_clean.loc[country1_clean["Source"] < 2]
#country_name_clean_nan[country_name_clean_nan["Country Name"] == "Timor"]
#search = country_name_clean_nan["Country Name"].str.contains("had")
#country_name_clean_nan[search]
#country1_clean.head(20)
#country_name_nan.shape

                                 Source
Country Name
Anguilla                              1
Bonaire Sint Eustatius and Saba       1
Burkina Faso                          1
Burma                                 1
Burundi                               1
Cabo Verde                            1
Cape Verde                            1
Chad                                  1
Congo                                 1
Congo (Brazzaville)                   1
Congo (Kinshasa)                      1
Democratic Republic of Congo          1
Diamond Princess                      1
England                               1
Eritrea                               1
Faeroe Islands                        1
Falkland Islands                      1
Guernsey                              1
Haiti                                 1
Holy See                              1
Jersey                                1
Korea, South                          1
MS Zaandam                            1
Macao                                 1
Marshall Islands                      1
Micronesia                            1
Montserrat                            1
Myanmar                               1
Nauru                                 1
New Caledonia                         1
Northern Cyprus                       1
Northern Ireland                      1
Palestine                             1
Saint Helena                          1
Scotland                              1
Sint Maarten                          1
Sint Maarten (Dutch part)             1
South Korea                           1
St. Martin (French part)              1
Taiwan                                1
Taiwan*                               1
Tanzania                              1
Timor                                 1
Timor-Leste                           1
Tonga                                 1
Turkmenistan                          1
Tuvalu                                1
US                                    1
United States                         1
Vanuatu                               1
Wales                                 1
Wallis and Futuna                     1
West Bank and Gaza                    1

In [79]:
#country name changes needed clean
search = country_name_clean_nan["Country Name"].str.contains("aza")
country_name_clean_nan[search]

           Country Name       Source
93           Kazakhstan   loc_name_c
200  West Bank and Gaza   loc_name_c
301          Kazakhstan  vacs_name_c

In [141]:
#check gdp and pop country name
list_name_clean_gp = []
list_source_clean_gp = []

for name in gdp_country_2019:
    list_name_clean_gp.append(name)
    list_source_clean_gp.append("gdp_name")
    
for name in pop_country_2019:
    list_name_clean_gp.append(name)
    list_source_clean_gp.append("pop_name")
    
country_names_clean_gp = pd.DataFrame({"Country Name": list_name_clean_gp,
                                        "Source": list_source_clean_gp
                                    })
country_name_clean_gp_nan = country_names_clean_gp.dropna()
country1_clean_gp = country_name_clean_gp_nan.groupby('Country Name').count()
country1_clean_gp.sort_values("Source")
#country1_clean_gp.loc[country1_clean_gp["Source"] < 2]
#country name changes needed clean
#search_gp = country_name_clean_gp_nan["Country Name"].str.contains("orea")
#country_name_clean_gp_nan[search_gp]
#merge gdp and pop data 2019
pop_gp_2019_merge = pop_raw_2019_df.merge(gdp_raw_2019_df, on="Country", how="inner")
pop_gdp_2019_merge["2019 Population"] = pop_gp_2019_merge["2019 Population"].fillna(0)
pop_gdp_2019_merge["2019 GDP"] = pop_gp_2019_merge["2019 GDP"].fillna(0)
pop_gdp_2019_merge1 = pop_gdp_2019_merge.copy()
#search_gp = pop_gdp_2019_merge1["Country"].str.contains("aza")
#pop_gdp_2019_merge1[search_gp]
#pop_gdp_2019_merge1.to_csv("pop_gdp_2019_merge.csv", index=False)

In [ ]:
#country name changes needed
#gpd
Yemen, Rep. : Yemen
Wallis and Futuna : France
#pop
Yemen, Rep. : Yemen
Wallis and Futuna : France
#vacs
Timor : Timor-Leste